version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet pack ./Ksuid/Ksuid.csproj -c Release
after_build:
  # For once the build has completed
artifacts:
 - path: '\Ksuid\bin\Release'
   name: Ksuid
   type: NuGetPackage
clone_depth: 1
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: cd ./Ksuid.Test
  - cmd: dotnet xunit
deploy: off
